### ISSUE TITLE
npm install doesnt work as needed

### ISSUE THREAD

**Issue by ArtemChik103** [xoderton/osutify#9]
**PS C:\Users\pvppv\osutify> npm install
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: next@15.0.0-rc.0
npm error Found: react@19.0.0-rc-4c2e457c7c-20240522
npm error node_modules/react
npm error   peer react@"^16.8 || ^17.0 || ^18.0 || ^19.0 || ^19.0.0-rc" from @radix-ui/react-collection@1.1.0
npm error   node_modules/@radix-ui/react-collection
npm error     @radix-ui/react-collection@"1.1.0" from @radix-ui/react-slider@1.2.0
npm error     node_modules/@radix-ui/react-slider
npm error       @radix-ui/react-slider@"^1.1.2" from the root project
npm error   peer react@"^16.8 || ^17.0 || ^18.0 || ^19.0 || ^19.0.0-rc" from @radix-ui/react-compose-refs@1.1.0
npm error   node_modules/@radix-ui/react-compose-refs
npm error     @radix-ui/react-compose-refs@"1.1.0" from @radix-ui/react-collection@1.1.0
npm error     node_modules/@radix-ui/react-collection
npm error       @radix-ui/react-collection@"1.1.0" from @radix-ui/react-slider@1.2.0
npm error       node_modules/@radix-ui/react-slider
npm error         @radix-ui/react-slider@"^1.1.2" from the root project
npm error     @radix-ui/react-compose-refs@"1.1.0" from @radix-ui/react-slider@1.2.0
npm error     node_modules/@radix-ui/react-slider
npm error       @radix-ui/react-slider@"^1.1.2" from the root project
npm error     1 more (@radix-ui/react-slot)
npm error   13 more (@radix-ui/react-context, @radix-ui/react-direction, ...)
npm error
npm error Could not resolve dependency:
npm error peer react@"19.0.0-rc-f994737d14-20240522" from next@15.0.0-rc.0
npm error node_modules/next
npm error   next@"^15.0.0-rc.0" from the root project
npm error
npm error Conflicting peer dependency: react@19.0.0-rc-f994737d14-20240522
npm error node_modules/react
npm error   peer react@"19.0.0-rc-f994737d14-20240522" from next@15.0.0-rc.0
npm error   node_modules/next
npm error     next@"^15.0.0-rc.0" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error C:\Users\pvppv\AppData\Local\npm-cache\_logs\2024-08-14T18_22_24_883Z-eresolve-report.txt
npm error A complete log of this run can be found in: C:\Users\pvppv\AppData\Local\npm-cache\_logs\2024-08-14T18_22_24_883Z-debug-0.log**

**Comment by shockpast** [comment]
`npm install` doesn't work on `feature/tauri` because some of dependencies *(react and next apparently)* uses legacy/conflicting sub-dependencies, it will be noted after this issue.

## Solution
Use `npm install --force`
